# Generated by Django 4.2.3 on 2023-07-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='available',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
